version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map container port to host port
    volumes:
      - .:/app  
    environment:
      - ENV=production
